export type TemplateItem = {
  id: number
  order: number
  active: boolean
  title: string
  subtitle: string
  category: string
  urlImage: string
  tags: string[]
  demoUrl: string
  htmlFile: string
}

export const templateItems: TemplateItem[] = [
  {
    id: 11,
    order: 1,
    active: true,
    title: "Nexus Studio Demo",
    subtitle: "Template demo completo do Nexus Studio, ideal para download em arquivo HTML unico.",
    category: "Demo",
    urlImage: "/nexus-demo.png",
    demoUrl: "/nexus-demo",
    tags: ["Demo", "Landing", "Download"],
    htmlFile: "NexusTemplate.html",
  },
  {
    id: 1,
    order: 2,
    active: true,
    title: "SaaS Starter",
    subtitle:
      "Complete SaaS landing page with pricing, features, and testimonials. Perfect for launching your subscription business.",
    category: "SaaS",
    urlImage: "/saasflow-hero.png",
    demoUrl: "#",
    tags: ["Next.js", "Stripe", "Auth"],
    htmlFile: "saas-starter.html",
  },
  {
    id: 2,
    order: 3,
    active: true,
    title: "AI Chatbot",
    subtitle:
      "Full-featured AI chatbot interface built with Vercel AI SDK, OpenAI, and real-time streaming responses.",
    category: "AI",
    urlImage: "/aiChatbot.png",
    demoUrl: "#",
    tags: ["AI SDK", "OpenAI", "Chat"],
    htmlFile: "ai-chatbot.html",
  },
  {
    id: 3,
    order: 4,
    active: true,
    title: "E-commerce Store",
    subtitle: "Modern e-commerce storefront with product catalog, shopping cart, and Stripe checkout integration.",
    category: "E-commerce",
    urlImage: "/ecomerce-shop.png",
    demoUrl: "#",
    tags: ["Stripe", "Cart", "Products"],
    htmlFile: "e-commerce-store.html",
  },
  {
    id: 4,
    order: 5,
    active: true,
    title: "Portfolio Pro",
    subtitle: "Minimalist portfolio template for designers and developers. Showcase your work with style.",
    category: "Portfolio",
    urlImage: "/portfolioPro.png",
    demoUrl: "#",
    tags: ["Portfolio", "Showcase", "MDX"],
    htmlFile: "portfolio-pro.html",
  },
  {
    id: 5,
    order: 6,
    active: true,
    title: "Blog Platform",
    subtitle: "Feature-rich blog with markdown support, SEO optimization, and beautiful typography.",
    category: "Blog",
    urlImage: "/blog.png",
    demoUrl: "#",
    tags: ["Blog", "MDX", "SEO"],
    htmlFile: "blog-platform.html",
  },
  {
    id: 6,
    order: 7,
    active: true,
    title: "Admin Dashboard",
    subtitle: "Comprehensive admin dashboard with analytics, charts, and data tables. Built with shadcn/ui.",
    category: "Dashboard",
    urlImage: "/admin-dashboard.png",
    demoUrl: "#",
    tags: ["Dashboard", "Analytics", "Tables"],
    htmlFile: "admin-dashboard.html",
  },
  {
    id: 7,
    order: 8,
    active: true,
    title: "Agency Website",
    subtitle: "Stunning agency landing page with hero section, services showcase, and contact form.",
    category: "Agency",
    urlImage: "/agency-website.png",
    demoUrl: "#",
    tags: ["Agency", "Landing", "Forms"],
    htmlFile: "agency-website.html",
  },
  {
    id: 8,
    order: 9,
    active: true,
    title: "Documentation Site",
    subtitle: "Clean documentation template with sidebar navigation, search, and code highlighting.",
    category: "Docs",
    urlImage: "/documentation.png",
    demoUrl: "#",
    tags: ["Docs", "MDX", "Search"],
    htmlFile: "documentation-site.html",
  },
  {
    id: 9,
    order: 10,
    active: true,
    title: "Social Network",
    subtitle: "Social media starter with user profiles, posts feed, likes, and comments functionality.",
    category: "Social",
    urlImage: "/social.png",
    demoUrl: "#",
    tags: ["Social", "Auth", "Supabase"],
    htmlFile: "social-network.html",
  },
  {
    id: 10,
    order: 11,
    active: true,
    title: "Startup MVP",
    subtitle: "All-in-one startup template with waitlist, auth, dashboard, and payment integration.",
    category: "Startup",
    urlImage: "/startup.png",
    demoUrl: "#",
    tags: ["Startup", "Auth", "Payments"],
    htmlFile: "startup-mvp.html",
  },
]
